export const COMPLETE_ASSIGNMENT = "COMPLETE_ASSIGNMENT";
export const UPDATE_ASSIGNMENT_TYPE = "UPDATE_ASSIGNMENT_TYPE";
export const UPDATE_ASSIGNMENT_DIFFICULTY = "UPDATE_ASSIGNMENT_DIFFICULTY";

export const LIST_ASSIGNMENTS = "LIST_ASSIGNMENTS";
export const SET_ASSIGNMENTS_LIST = "SET_ASSIGNMENTS_LIST";
